### ISSUE TITLE
Cannot create regular file

### ISSUE THREAD

**Issue by B10inform** [eliza-m/LRRpredictor_v1#3]
Hi, 

I tried with docker and building from source. Both are giving me similar type of error

Error with docker have been posted in **"Failed in generating TGT file #1"**

Error with source:

**LRRpredictor_v1$ python3 LRRpred.py gpa2.fasta results**

Checking environment variables... OK
Checking fasta file... OK
Runing HHsuite and RaptorX-Property :
<<
cp: cannot create regular file '/home/GitBucket/RaptorX_Property_Fast/gpa2.fasta': No such file or directory
/home/LRRpredictor_v1/RaptorX_Property_Fast/oneline_command.sh: line 42: cd: /home/GitBucket/RaptorX_Property_Fast: No such file or directory
Running Fast_TGT to generate TGT file for sequence gpa2
Failed in generating TGT file for sequence gpa2
mkdir: cannot create directory ‘results/gpa2’: No such file or directory
mkdir: cannot create directory ‘results/gpa2/RaptorX-Property/’: No such file or directory
mv: cannot stat '/home/LRRpredictor_v1/RaptorX_Property_Fast/tmp/gpa2/*': No such file or directory
/home/LRRpredictor_v1/util/getInputData.sh: line 14: results/gpa2/gpa2.pssm: No such file or directory
/home/LRRpredictor_v1/util/getInputData.sh: line 17: results/gpa2/gpa2.input: No such file or directory
[Errno 2] No such file or directory: 'results/gpa2/gpa2.input'

Any information would be really nice.

**Comment by eliza-m** [comment]
Hi,


Please find some comments and questions regarding the docker error within its issue it was initially posted - [here](https://github.com/eliza-m/LRRpredictor_v1/issues/1).

Regarding the error retrieved when building from source, thank you for noticing this !

This error relates to a path issue in the original branch of Raptor, however, I thought this was solved in the branch used by LRRpredictor.

Could you please go to the Raptor home folder and run :
`git status` 


I added bellow a full list of instructions to build all the dependencies. The only thing that needs to be changed is the path for Uniprot20.

```
git clone --recursive https://github.com/eliza-m/LRRpredictor_v1.git

# Exporting some variables

echo "export LRRpredictor_HOME="$(pwd)"/LRRpredictor_v1" >> ~/.bashrc
echo "export RaptorX_HOME="$(pwd)"/LRRpredictor_v1/RaptorX_Property_Fast" >> ~/.bashrc
echo "export HHSUITE_HOME="$(pwd)"/LRRpredictor_v1/hh-suite" >> ~/.bashrc
export HHSUITE_INSTALL_BASE_DIR=$(pwd)/LRRpredictor_v1/hh-suite	
echo "export HHLIB="${HHSUITE_INSTALL_BASE_DIR} >> ~/.bashrc
echo 'export PATH=${PATH}:'${HHSUITE_INSTALL_BASE_DIR}"/bin:"${HHSUITE_INSTALL_BASE_DIR}"/scripts" >> ~/.bashrc

export MakeNoOfThreads=4

# This needs to be changed !!
echo "export UNIPROT20_PATH=/.../.../uniprot20" >> ~/.bashrc



source ~/.bashrc



echo "Building HH-suite... "

cd $HHSUITE_HOME
git checkout LRRpredictor
mkdir lib
cd lib
git clone https://github.com/eliza-m/ffindex_soedinglab.git ffindex
cd ffindex
git checkout 360e417
cd ../../
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=${HHSUITE_INSTALL_BASE_DIR} ..
make -j $MakeNoOfThreads
make install

echo "Installing HH-suite... DONE"



echo "Building RaptorX-Property..."

cd ${RaptorX_HOME}
git checkout LRRpredictor
cd source_code
make -j $MakeNoOfThreads
cd ../
./setup.pl

cd databases
rm uniprot20
ln -s ${UNIPROT20_PATH} uniprot20

echo "Building RaptorX-Property... DONE "



cd $LRRpredictor_HOME/fullTraining/

wget old.biochim.ro/ib/departments/strbiochem/LRRpred/fullTraining_pkls.tar.gz
tar -xzf fullTraining_pkls.tar.gz
mv fullTraining_pkls/* ./
rm fullTraining_pkls.tar.gz
rmdir fullTraining_pkls


# Testing the installation

cd $LRRpredictor_HOME
mkdir results

python3 LRRpred.py gpa2.fasta results

```

Could you please let me know if it worked or the same error appears?
Thanks !

Best regards,
Eliza

**Comment by B10inform** [comment]
Hi Eliza,

I am getting these errors.

**LRRpredictor_v1$ python3 LRRpred.py gpa2.fasta results**
Traceback (most recent call last):
  File "LRRpred.py", line 13, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib'

*changed "from sklearn.externals import joblib" to "import joblib"*


**LRRpredictor_v1$ python3 LRRpred.py gpa2.fasta results**

Checking environment variables... OK
Checking fasta file... OK
Runing HHsuite and RaptorX-Property :
<<
Running Fast_TGT to generate TGT file for sequence gpa2
Failed in generating TGT file for sequence gpa2
mv: cannot stat '/home/LRRpredictor_v1/RaptorX_Property_Fast/tmp/gpa2/*': No such file or directory
awk: cmd. line:1: fatal: cannot open file `results/gpa2/RaptorX-Property/gpa2.tgt2' for reading (No such file or directory)
Traceback (most recent call last):
  File "/home/LRRpredictor_v1/util/getInputData.py", line 9, in <module>
    ss3file = open( outputFolder + "/" + fastaFileRoot + "/RaptorX-Property/" + fastaFileRoot + ".ss3", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'results/gpa2/RaptorX-Property/gpa2.ss3'

>>
Input data was generated
LRRpredictor - classifer  1 / 8 ...
/home/.local/lib/python3.6/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator SVC from version 0.22 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/.local/lib/python3.6/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.22 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/.local/lib/python3.6/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator _SigmoidCalibration from version 0.22 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/.local/lib/python3.6/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator CalibratedClassifierCV from version 0.22 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "LRRpred.py", line 84, in <module>
    testset_pred.append( classifiers[ currentClf ].predict(features) )
  File "/home/.local/lib/python3.6/site-packages/sklearn/calibration.py", line 385, in predict
    return self.classes_[np.argmax(self.predict_proba(X), axis=1)]
  File "/home/.local/lib/python3.6/site-packages/sklearn/calibration.py", line 357, in predict_proba
    force_all_finite=False)
  File "/home/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 641, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
